version: 2

build:
  image: testing # Because Python 3.9 is only available in "testing".

sphinx:
  configuration: docs/conf.py

python:
  # Use 3.9 instead of 3.10 due to errors.
  version: "3.9"
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
