version: 2

build:
  image: testing # Because Python 3.9 is only available in "testing".

sphinx:
  configuration: docs/conf.py

python:
  version: "3.10"
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
