plugins:
  - mkdocstrings:
      default_handler: python
  - search
nav:
  - Home: index.md
  - get-started/tutorial.md
  - get-started/how-it-works.md
  - Features:
      - features/events.md
      - features/templating.md
      - features/custom-config.md
  - Examples:
      - examples/simple/index.md
      - examples/load_file/index.md
      - examples/multiple_tasks/index.md
  - Reference:
      - reference/configuration.md
      - reference/task.md
      - reference/filters.md
      - reference/actions.md
  - contributing.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
repo_name: wndhydrnt/rcmt
repo_url: https://github.com/wndhydrnt/rcmt
site_name: rcmt
theme:
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.sections
  name: material
