# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.18.0+1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import rcmt.source.gitea.client
from rcmt.source.gitea.client.models.changed_file import ChangedFile  # noqa: E501
from rcmt.source.gitea.client.rest import ApiException

class TestChangedFile(unittest.TestCase):
    """ChangedFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ChangedFile
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = rcmt.source.gitea.client.models.changed_file.ChangedFile()  # noqa: E501
        if include_optional :
            return ChangedFile(
                additions = 56, 
                changes = 56, 
                contents_url = '', 
                deletions = 56, 
                filename = '', 
                html_url = '', 
                previous_filename = '', 
                raw_url = '', 
                status = ''
            )
        else :
            return ChangedFile(
        )

    def testChangedFile(self):
        """Test ChangedFile"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
