on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test and build main
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore')"
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: Gr1N/setup-poetry@v9
      - run: poetry install --all-extras
      - run: make lint
      - run: make test
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_CREDS_USR }}
          password: ${{ secrets.DOCKER_CREDS_PSW }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          config: .github/buildkitd.toml
      - name: Push Docker image
        env:
          RCMT_VERSION: main
        run: |
          make docker_push
