on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test and build main
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'chore')"
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: Gr1N/setup-poetry@v8
      - run: poetry install --extras "semgrep"
      - run: make lint
      - run: make test
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_CREDS_USR }}
          password: ${{ secrets.DOCKER_CREDS_PSW }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          config: .github/buildkitd.toml
      - name: Push Docker image
        env:
          RCMT_VERSION: main
        run: |
          make docker_push
