name: Pull Request

on:
  pull_request: {}

jobs:
  docs:
    name: Validate documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: Gr1N/setup-poetry@v9
      - run: poetry install --with docs
      - run: make docs
  license:
    name: Ensure all files contain MPL 2.0 header
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: apache/skywalking-eyes/header@3ea9df11bb3a5a85665377d1fd10c02edecf2c40
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - uses: Gr1N/setup-poetry@v9
      - run: poetry install --all-extras
      - run: make lint
      - run: make test
