on:
  pull_request: {}

jobs:
  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: Gr1N/setup-poetry@v8
      - run: poetry install --with docs
      - run: make docs
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - uses: Gr1N/setup-poetry@v8
      - run: poetry install --extras "semgrep"
      - run: make lint
      - run: make test
