on:
  pull_request: {}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.version }}
      - uses: Gr1N/setup-poetry@v5
      - run: poetry install
      - run: poetry env info
      - run: poetry show --tree
#      - run: make lint
#      - run: make test
