on:
  pull_request: {}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.version }}
      - uses: Gr1N/setup-poetry@v8
      - run: poetry install
      - run: make lint
      - run: make test
