on:
  pull_request: {}

jobs:
  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: Gr1N/setup-poetry@v8
      - run: poetry install --with docs
      - run: make docs
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - uses: Gr1N/setup-poetry@v8
      - run: poetry install --extras "semgrep"
      - run: make lint
      - run: make test
