on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - uses: Gr1N/setup-poetry@v8
      - env:
          PUBLISH_USERNAME: ${{ secrets.PUBLISH_USERNAME }}
          PUBLISH_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
        run: make publish
      - name: Extract tag from ref
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_CREDS_USR }}
          password: ${{ secrets.DOCKER_CREDS_PSW }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          config: .github/buildkitd.toml
      - name: Push Docker image
        env:
          RCMT_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          make docker_push
