# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.18.0+1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from rcmt.source.gitea.client.configuration import Configuration


class CreateBranchRepoOption(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'new_branch_name': 'str',
        'old_branch_name': 'str'
    }

    attribute_map = {
        'new_branch_name': 'new_branch_name',
        'old_branch_name': 'old_branch_name'
    }

    def __init__(self, new_branch_name=None, old_branch_name=None, local_vars_configuration=None):  # noqa: E501
        """CreateBranchRepoOption - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._new_branch_name = None
        self._old_branch_name = None
        self.discriminator = None

        self.new_branch_name = new_branch_name
        if old_branch_name is not None:
            self.old_branch_name = old_branch_name

    @property
    def new_branch_name(self):
        """Gets the new_branch_name of this CreateBranchRepoOption.  # noqa: E501

        Name of the branch to create  # noqa: E501

        :return: The new_branch_name of this CreateBranchRepoOption.  # noqa: E501
        :rtype: str
        """
        return self._new_branch_name

    @new_branch_name.setter
    def new_branch_name(self, new_branch_name):
        """Sets the new_branch_name of this CreateBranchRepoOption.

        Name of the branch to create  # noqa: E501

        :param new_branch_name: The new_branch_name of this CreateBranchRepoOption.  # noqa: E501
        :type new_branch_name: str
        """
        if self.local_vars_configuration.client_side_validation and new_branch_name is None:  # noqa: E501
            raise ValueError("Invalid value for `new_branch_name`, must not be `None`")  # noqa: E501

        self._new_branch_name = new_branch_name

    @property
    def old_branch_name(self):
        """Gets the old_branch_name of this CreateBranchRepoOption.  # noqa: E501

        Name of the old branch to create from  # noqa: E501

        :return: The old_branch_name of this CreateBranchRepoOption.  # noqa: E501
        :rtype: str
        """
        return self._old_branch_name

    @old_branch_name.setter
    def old_branch_name(self, old_branch_name):
        """Sets the old_branch_name of this CreateBranchRepoOption.

        Name of the old branch to create from  # noqa: E501

        :param old_branch_name: The old_branch_name of this CreateBranchRepoOption.  # noqa: E501
        :type old_branch_name: str
        """

        self._old_branch_name = old_branch_name

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateBranchRepoOption):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateBranchRepoOption):
            return True

        return self.to_dict() != other.to_dict()
