# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.18.0+1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from rcmt.source.gitea.client.configuration import Configuration


class CreatePushMirrorOption(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'interval': 'str',
        'remote_address': 'str',
        'remote_password': 'str',
        'remote_username': 'str'
    }

    attribute_map = {
        'interval': 'interval',
        'remote_address': 'remote_address',
        'remote_password': 'remote_password',
        'remote_username': 'remote_username'
    }

    def __init__(self, interval=None, remote_address=None, remote_password=None, remote_username=None, local_vars_configuration=None):  # noqa: E501
        """CreatePushMirrorOption - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._interval = None
        self._remote_address = None
        self._remote_password = None
        self._remote_username = None
        self.discriminator = None

        if interval is not None:
            self.interval = interval
        if remote_address is not None:
            self.remote_address = remote_address
        if remote_password is not None:
            self.remote_password = remote_password
        if remote_username is not None:
            self.remote_username = remote_username

    @property
    def interval(self):
        """Gets the interval of this CreatePushMirrorOption.  # noqa: E501


        :return: The interval of this CreatePushMirrorOption.  # noqa: E501
        :rtype: str
        """
        return self._interval

    @interval.setter
    def interval(self, interval):
        """Sets the interval of this CreatePushMirrorOption.


        :param interval: The interval of this CreatePushMirrorOption.  # noqa: E501
        :type interval: str
        """

        self._interval = interval

    @property
    def remote_address(self):
        """Gets the remote_address of this CreatePushMirrorOption.  # noqa: E501


        :return: The remote_address of this CreatePushMirrorOption.  # noqa: E501
        :rtype: str
        """
        return self._remote_address

    @remote_address.setter
    def remote_address(self, remote_address):
        """Sets the remote_address of this CreatePushMirrorOption.


        :param remote_address: The remote_address of this CreatePushMirrorOption.  # noqa: E501
        :type remote_address: str
        """

        self._remote_address = remote_address

    @property
    def remote_password(self):
        """Gets the remote_password of this CreatePushMirrorOption.  # noqa: E501


        :return: The remote_password of this CreatePushMirrorOption.  # noqa: E501
        :rtype: str
        """
        return self._remote_password

    @remote_password.setter
    def remote_password(self, remote_password):
        """Sets the remote_password of this CreatePushMirrorOption.


        :param remote_password: The remote_password of this CreatePushMirrorOption.  # noqa: E501
        :type remote_password: str
        """

        self._remote_password = remote_password

    @property
    def remote_username(self):
        """Gets the remote_username of this CreatePushMirrorOption.  # noqa: E501


        :return: The remote_username of this CreatePushMirrorOption.  # noqa: E501
        :rtype: str
        """
        return self._remote_username

    @remote_username.setter
    def remote_username(self, remote_username):
        """Sets the remote_username of this CreatePushMirrorOption.


        :param remote_username: The remote_username of this CreatePushMirrorOption.  # noqa: E501
        :type remote_username: str
        """

        self._remote_username = remote_username

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreatePushMirrorOption):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreatePushMirrorOption):
            return True

        return self.to_dict() != other.to_dict()
