# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.18.0+1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from rcmt.source.gitea.client.configuration import Configuration


class CreateStatusOption(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'context': 'str',
        'description': 'str',
        'state': 'str',
        'target_url': 'str'
    }

    attribute_map = {
        'context': 'context',
        'description': 'description',
        'state': 'state',
        'target_url': 'target_url'
    }

    def __init__(self, context=None, description=None, state=None, target_url=None, local_vars_configuration=None):  # noqa: E501
        """CreateStatusOption - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._context = None
        self._description = None
        self._state = None
        self._target_url = None
        self.discriminator = None

        if context is not None:
            self.context = context
        if description is not None:
            self.description = description
        if state is not None:
            self.state = state
        if target_url is not None:
            self.target_url = target_url

    @property
    def context(self):
        """Gets the context of this CreateStatusOption.  # noqa: E501


        :return: The context of this CreateStatusOption.  # noqa: E501
        :rtype: str
        """
        return self._context

    @context.setter
    def context(self, context):
        """Sets the context of this CreateStatusOption.


        :param context: The context of this CreateStatusOption.  # noqa: E501
        :type context: str
        """

        self._context = context

    @property
    def description(self):
        """Gets the description of this CreateStatusOption.  # noqa: E501


        :return: The description of this CreateStatusOption.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CreateStatusOption.


        :param description: The description of this CreateStatusOption.  # noqa: E501
        :type description: str
        """

        self._description = description

    @property
    def state(self):
        """Gets the state of this CreateStatusOption.  # noqa: E501

        CommitStatusState holds the state of a CommitStatus It can be \"pending\", \"success\", \"error\", \"failure\", and \"warning\"  # noqa: E501

        :return: The state of this CreateStatusOption.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this CreateStatusOption.

        CommitStatusState holds the state of a CommitStatus It can be \"pending\", \"success\", \"error\", \"failure\", and \"warning\"  # noqa: E501

        :param state: The state of this CreateStatusOption.  # noqa: E501
        :type state: str
        """

        self._state = state

    @property
    def target_url(self):
        """Gets the target_url of this CreateStatusOption.  # noqa: E501


        :return: The target_url of this CreateStatusOption.  # noqa: E501
        :rtype: str
        """
        return self._target_url

    @target_url.setter
    def target_url(self, target_url):
        """Sets the target_url of this CreateStatusOption.


        :param target_url: The target_url of this CreateStatusOption.  # noqa: E501
        :type target_url: str
        """

        self._target_url = target_url

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateStatusOption):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateStatusOption):
            return True

        return self.to_dict() != other.to_dict()
