# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.18.0+1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from rcmt.source.gitea.client.configuration import Configuration


class NodeInfoUsage(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'local_comments': 'int',
        'local_posts': 'int',
        'users': 'NodeInfoUsageUsers'
    }

    attribute_map = {
        'local_comments': 'localComments',
        'local_posts': 'localPosts',
        'users': 'users'
    }

    def __init__(self, local_comments=None, local_posts=None, users=None, local_vars_configuration=None):  # noqa: E501
        """NodeInfoUsage - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._local_comments = None
        self._local_posts = None
        self._users = None
        self.discriminator = None

        if local_comments is not None:
            self.local_comments = local_comments
        if local_posts is not None:
            self.local_posts = local_posts
        if users is not None:
            self.users = users

    @property
    def local_comments(self):
        """Gets the local_comments of this NodeInfoUsage.  # noqa: E501


        :return: The local_comments of this NodeInfoUsage.  # noqa: E501
        :rtype: int
        """
        return self._local_comments

    @local_comments.setter
    def local_comments(self, local_comments):
        """Sets the local_comments of this NodeInfoUsage.


        :param local_comments: The local_comments of this NodeInfoUsage.  # noqa: E501
        :type local_comments: int
        """

        self._local_comments = local_comments

    @property
    def local_posts(self):
        """Gets the local_posts of this NodeInfoUsage.  # noqa: E501


        :return: The local_posts of this NodeInfoUsage.  # noqa: E501
        :rtype: int
        """
        return self._local_posts

    @local_posts.setter
    def local_posts(self, local_posts):
        """Sets the local_posts of this NodeInfoUsage.


        :param local_posts: The local_posts of this NodeInfoUsage.  # noqa: E501
        :type local_posts: int
        """

        self._local_posts = local_posts

    @property
    def users(self):
        """Gets the users of this NodeInfoUsage.  # noqa: E501


        :return: The users of this NodeInfoUsage.  # noqa: E501
        :rtype: NodeInfoUsageUsers
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this NodeInfoUsage.


        :param users: The users of this NodeInfoUsage.  # noqa: E501
        :type users: NodeInfoUsageUsers
        """

        self._users = users

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NodeInfoUsage):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NodeInfoUsage):
            return True

        return self.to_dict() != other.to_dict()
