# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.18.0+1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from rcmt.source.gitea.client.configuration import Configuration


class PullReviewRequestOptions(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'reviewers': 'list[str]',
        'team_reviewers': 'list[str]'
    }

    attribute_map = {
        'reviewers': 'reviewers',
        'team_reviewers': 'team_reviewers'
    }

    def __init__(self, reviewers=None, team_reviewers=None, local_vars_configuration=None):  # noqa: E501
        """PullReviewRequestOptions - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._reviewers = None
        self._team_reviewers = None
        self.discriminator = None

        if reviewers is not None:
            self.reviewers = reviewers
        if team_reviewers is not None:
            self.team_reviewers = team_reviewers

    @property
    def reviewers(self):
        """Gets the reviewers of this PullReviewRequestOptions.  # noqa: E501


        :return: The reviewers of this PullReviewRequestOptions.  # noqa: E501
        :rtype: list[str]
        """
        return self._reviewers

    @reviewers.setter
    def reviewers(self, reviewers):
        """Sets the reviewers of this PullReviewRequestOptions.


        :param reviewers: The reviewers of this PullReviewRequestOptions.  # noqa: E501
        :type reviewers: list[str]
        """

        self._reviewers = reviewers

    @property
    def team_reviewers(self):
        """Gets the team_reviewers of this PullReviewRequestOptions.  # noqa: E501


        :return: The team_reviewers of this PullReviewRequestOptions.  # noqa: E501
        :rtype: list[str]
        """
        return self._team_reviewers

    @team_reviewers.setter
    def team_reviewers(self, team_reviewers):
        """Sets the team_reviewers of this PullReviewRequestOptions.


        :param team_reviewers: The team_reviewers of this PullReviewRequestOptions.  # noqa: E501
        :type team_reviewers: list[str]
        """

        self._team_reviewers = team_reviewers

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PullReviewRequestOptions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PullReviewRequestOptions):
            return True

        return self.to_dict() != other.to_dict()
