# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.18.0+1
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from rcmt.source.gitea.client.configuration import Configuration


class WikiCommitList(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'commits': 'list[WikiCommit]',
        'count': 'int'
    }

    attribute_map = {
        'commits': 'commits',
        'count': 'count'
    }

    def __init__(self, commits=None, count=None, local_vars_configuration=None):  # noqa: E501
        """WikiCommitList - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._commits = None
        self._count = None
        self.discriminator = None

        if commits is not None:
            self.commits = commits
        if count is not None:
            self.count = count

    @property
    def commits(self):
        """Gets the commits of this WikiCommitList.  # noqa: E501


        :return: The commits of this WikiCommitList.  # noqa: E501
        :rtype: list[WikiCommit]
        """
        return self._commits

    @commits.setter
    def commits(self, commits):
        """Sets the commits of this WikiCommitList.


        :param commits: The commits of this WikiCommitList.  # noqa: E501
        :type commits: list[WikiCommit]
        """

        self._commits = commits

    @property
    def count(self):
        """Gets the count of this WikiCommitList.  # noqa: E501


        :return: The count of this WikiCommitList.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this WikiCommitList.


        :param count: The count of this WikiCommitList.  # noqa: E501
        :type count: int
        """

        self._count = count

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WikiCommitList):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, WikiCommitList):
            return True

        return self.to_dict() != other.to_dict()
